spring:
  application:
    name: consumer-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
server:
  port: 10000

consumer-age: 30